# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://JimmyWhitaker.github.io/pachderm_tutorial/"

git_url = "https://github.com/JimmyWhitaker/pachderm_tutorial/tree/master/"

def custom_doc_links(name): return None
